1. a = np.array([
 [11,22,33],
 [44,55,66],
 [77,88,99]
])


Extract:
- first column
- last row
- [
 [22 33]
 [55 66]
 ]

In [1]:
import numpy as np

In [2]:
a = np.array([
 [11,22,33],
 [44,55,66],
 [77,88,99]
])
print(a[:,:1])
print(a[2])
print(a[:2,1:])

[[11]
 [44]
 [77]]
[77 88 99]
[[22 33]
 [55 66]]


2. a = np.array([
 [10,20,30],
 [40,50,60],
 [70,80,90]
])


Extract:
- first row
- second column
- element 50

In [3]:
a = np.array([
 [10,20,30],
 [40,50,60],
 [70,80,90]
])
print(a[0])
print(a[:,1])
print(a[1,1])

[10 20 30]
[20 50 80]
50


3. Create an array from 1 to 12 and reshape it into:
- (3,4)
- (2,6)
- (2,3,2)

In [4]:
a=np.arange(1,13)
print(a)
b=a.reshape(3,4)
print("\n Reshaped into (3,4):",b)
c=a.reshape(2,6)
print("\n Reshaped into (2,6):",c)
d=a.reshape(2,3,2)
print("\n Reshaped into (2,3,2):",d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

 Reshaped into (3,4): [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Reshaped into (2,6): [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

 Reshaped into (2,3,2): [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


4. a=np.array([1,2,3])

   b=np.array([4,5,6])

   Perform:
   
      - addition

      - substraction

      - multiplication

      - division

      - power of 3

      - square
   
      - mean

In [5]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Additon operation: ",a+b)
print("\n Substraction operation:",a-b)
print("\n Multiplication operation:",a*b)
print("\n Division operation: ",a/b)
print("\n power of 3 operation for a: ",a**3)
print("\n power of 3 operation for b: ",b**3)
print("\n Square operation for a: ",np.square(a))
print("\n Square operation for b: ",np.square(b))
print("\n Mean operation for a : ",np.mean(a))
print("\n Mean operation for b : ",np.mean(b))

Additon operation:  [5 7 9]

 Substraction operation: [-3 -3 -3]

 Multiplication operation: [ 4 10 18]

 Division operation:  [0.25 0.4  0.5 ]

 power of 3 operation for a:  [ 1  8 27]

 power of 3 operation for b:  [ 64 125 216]

 Square operation for a:  [1 4 9]

 Square operation for b:  [16 25 36]

 Mean operation for a :  2.0

 Mean operation for b :  5.0


5. Create a 1D array containing numbers from 1 to 10 using random module.
Create a 2D array of shape (3,3) containing numbers from 1 to 9 using random module.

In [6]:
a= np.random.randint(1,11,size=10)
print("1D Array: ",a)
b= np.random.randint(1,9,size=(3,3))
print("2D Array: ",b)

1D Array:  [8 3 9 5 3 2 1 6 9 1]
2D Array:  [[7 4 4]
 [4 1 3]
 [6 2 5]]



6. Generate a random array of shape (2,5).

In [7]:
a=np.random.random(10)
b=a.reshape(2,5)
print(b)

[[0.19984851 0.74339294 0.97254976 0.50166433 0.79099363]
 [0.90483906 0.03880049 0.28085664 0.66616176 0.32467407]]


- I am  trying  do two different methods here

In [8]:
a=np.random.rand(2,5)
print(a)

[[0.83135437 0.84956623 0.55267184 0.56352982 0.90140183]
 [0.82058972 0.32343661 0.15008632 0.17961623 0.015314  ]]


7. Difference between Python list and NumPy array.

Python list:
- It contains different datatypes(Heterogeneous).
- slower execution speed.
- Require manual loops or list comprehensions.

Numpy array:
- It contains all elements of same types.(Homogeneous)
- Faster execution speed.
- packed contiguously in a single memory block.
- Supports direct element-wise vector operations. 


8. Convert the following integer array into float datatype:
a = np.array([1,2,3,4])

In [9]:
a=np.array([1,2,3,4])
b=a.astype(float)
print(b)

[1. 2. 3. 4.]


9. What is the difference between:- dtype & astype()

dtype:- 

- check/return the data type of the object in numpy array series.

- It is an attribute.(No parenthesis required)

- It uses Zero Memory.

astype:-
- cast/convert to a new data type.

- It is a method.(Parenthesis required)
         
- It creates a new copy of your data in memory with the new type              

10. Create a 2D array and print:- shape- size- ndim- dtype
Change its datatype.

In [10]:
a= np.arange(1,11).reshape(2,5)
print(a)
print("\n Shape:",a.shape)
print("\n Size:",a.size)
print("\n Dimension:",a.ndim)
print("\n Data types of the element:",a.dtype)
b=a.astype(float)
print("\n The change after changing of the data type:",b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

 Shape: (2, 5)

 Size: 10

 Dimension: 2

 Data types of the element: int64

 The change after changing of the data type: [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


11. Can a 1D array be sliced like:
a[:,1]

Why or why not?

- No,we can't be sliced 1D array like this beacause this type of slicing particularly used for 2D array (it slices the 2nd column,generally which is not available in 1D array).
- The comma syntax separates slice instructions for different dimensions (axes).
- A syntax like [axis_0, axis_1] requires at least a 2D array.